-- Run this migration once in the existing Supabase project's SQL editor.
-- The Hono runtime never creates or alters tables in postgres mode.

create table if not exists packages (
  id integer generated by default as identity primary key,
  name text not null,
  price double precision not null,
  category text,
  description text,
  is_active integer not null default 1
);

create table if not exists invoices (
  id integer generated by default as identity primary key,
  invoice_no text,
  client_name text,
  date text,
  total_amount double precision,
  invoice_data text,
  pdf_blob bytea,
  payment_proofs text,
  is_archived integer not null default 0,
  created_at timestamptz not null default current_timestamp
);

create table if not exists invoice_activity_logs (
  id integer generated by default as identity primary key,
  invoice_id integer not null,
  action text not null,
  actor_id integer,
  actor_email text,
  actor_name text,
  actor_role text,
  details text,
  ip_address text,
  created_at timestamptz not null default current_timestamp
);

create index if not exists idx_invoice_activity_logs_invoice_id
  on invoice_activity_logs(invoice_id, created_at desc);

create table if not exists app_config (
  key text primary key,
  value text
);

create table if not exists users (
  id integer generated by default as identity primary key,
  email text not null unique,
  name text not null,
  password_hash text not null,
  role text not null default 'employee',
  created_at timestamptz not null default current_timestamp
);

create table if not exists user_permissions (
  id integer generated by default as identity primary key,
  user_id integer not null,
  permission_key text not null,
  effect text not null check (effect in ('grant', 'deny')),
  created_at timestamptz not null default current_timestamp,
  unique(user_id, permission_key)
);

create index if not exists idx_user_permissions_user_id
  on user_permissions(user_id);

create table if not exists user_activity_logs (
  id integer generated by default as identity primary key,
  action text not null,
  target_user_id integer,
  target_user_name text,
  target_user_email text,
  actor_id integer,
  actor_email text,
  actor_name text,
  actor_role text,
  details text,
  ip_address text,
  created_at timestamptz not null default current_timestamp
);

create index if not exists idx_user_activity_logs_created_at
  on user_activity_logs(created_at desc);

create table if not exists refresh_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null,
  token text not null unique,
  expires_at timestamptz not null,
  revoked integer not null default 0,
  created_at timestamptz not null default current_timestamp
);

create table if not exists audit_logs (
  id integer generated by default as identity primary key,
  event_type text not null,
  user_id integer,
  email text,
  ip_address text,
  user_agent text,
  success integer not null default 1,
  details text,
  created_at timestamptz not null default current_timestamp
);

create table if not exists sequences (
  name text primary key,
  prefix text,
  padding integer not null default 5,
  last_value integer not null default 0
);

insert into sequences(name, prefix, padding, last_value)
values ('invoice', 'INV', 5, 0)
on conflict (name) do nothing;
