/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PreweddingBaliRouteImport } from './routes/prewedding-bali'
import { Route as SangjitPhotographyJakartaRouteImport } from './routes/sangjit-photography-jakarta'
import { Route as WeddingPhotographerJakartaRouteImport } from './routes/wedding-photographer-jakarta'
import { Route as WeddingVideographerJakartaRouteImport } from './routes/wedding-videographer-jakarta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PreweddingBaliRoute = PreweddingBaliRouteImport.update({
  id: '/prewedding-bali',
  path: '/prewedding-bali',
  getParentRoute: () => rootRouteImport,
} as any)
const SangjitPhotographyJakartaRoute =
  SangjitPhotographyJakartaRouteImport.update({
    id: '/sangjit-photography-jakarta',
    path: '/sangjit-photography-jakarta',
    getParentRoute: () => rootRouteImport,
  } as any)
const WeddingPhotographerJakartaRoute =
  WeddingPhotographerJakartaRouteImport.update({
    id: '/wedding-photographer-jakarta',
    path: '/wedding-photographer-jakarta',
    getParentRoute: () => rootRouteImport,
  } as any)
const WeddingVideographerJakartaRoute =
  WeddingVideographerJakartaRouteImport.update({
    id: '/wedding-videographer-jakarta',
    path: '/wedding-videographer-jakarta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/prewedding-bali': typeof PreweddingBaliRoute
  '/sangjit-photography-jakarta': typeof SangjitPhotographyJakartaRoute
  '/wedding-photographer-jakarta': typeof WeddingPhotographerJakartaRoute
  '/wedding-videographer-jakarta': typeof WeddingVideographerJakartaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/prewedding-bali': typeof PreweddingBaliRoute
  '/sangjit-photography-jakarta': typeof SangjitPhotographyJakartaRoute
  '/wedding-photographer-jakarta': typeof WeddingPhotographerJakartaRoute
  '/wedding-videographer-jakarta': typeof WeddingVideographerJakartaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/prewedding-bali': typeof PreweddingBaliRoute
  '/sangjit-photography-jakarta': typeof SangjitPhotographyJakartaRoute
  '/wedding-photographer-jakarta': typeof WeddingPhotographerJakartaRoute
  '/wedding-videographer-jakarta': typeof WeddingVideographerJakartaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/packages'
    | '/portfolio'
    | '/prewedding-bali'
    | '/sangjit-photography-jakarta'
    | '/wedding-photographer-jakarta'
    | '/wedding-videographer-jakarta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/packages'
    | '/portfolio'
    | '/prewedding-bali'
    | '/sangjit-photography-jakarta'
    | '/wedding-photographer-jakarta'
    | '/wedding-videographer-jakarta'
  id:
    | '__root__'
    | '/'
    | '/packages'
    | '/portfolio'
    | '/prewedding-bali'
    | '/sangjit-photography-jakarta'
    | '/wedding-photographer-jakarta'
    | '/wedding-videographer-jakarta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackagesRoute: typeof PackagesRoute
  PortfolioRoute: typeof PortfolioRoute
  PreweddingBaliRoute: typeof PreweddingBaliRoute
  SangjitPhotographyJakartaRoute: typeof SangjitPhotographyJakartaRoute
  WeddingPhotographerJakartaRoute: typeof WeddingPhotographerJakartaRoute
  WeddingVideographerJakartaRoute: typeof WeddingVideographerJakartaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prewedding-bali': {
      id: '/prewedding-bali'
      path: '/prewedding-bali'
      fullPath: '/prewedding-bali'
      preLoaderRoute: typeof PreweddingBaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sangjit-photography-jakarta': {
      id: '/sangjit-photography-jakarta'
      path: '/sangjit-photography-jakarta'
      fullPath: '/sangjit-photography-jakarta'
      preLoaderRoute: typeof SangjitPhotographyJakartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-photographer-jakarta': {
      id: '/wedding-photographer-jakarta'
      path: '/wedding-photographer-jakarta'
      fullPath: '/wedding-photographer-jakarta'
      preLoaderRoute: typeof WeddingPhotographerJakartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-videographer-jakarta': {
      id: '/wedding-videographer-jakarta'
      path: '/wedding-videographer-jakarta'
      fullPath: '/wedding-videographer-jakarta'
      preLoaderRoute: typeof WeddingVideographerJakartaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackagesRoute: PackagesRoute,
  PortfolioRoute: PortfolioRoute,
  PreweddingBaliRoute: PreweddingBaliRoute,
  SangjitPhotographyJakartaRoute: SangjitPhotographyJakartaRoute,
  WeddingPhotographerJakartaRoute: WeddingPhotographerJakartaRoute,
  WeddingVideographerJakartaRoute: WeddingVideographerJakartaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
